//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.15 at 07:03:23 PM IST 
//


package testProj.test;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Header"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="PlanOrganization" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ActivityTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                   &lt;element name="LineOfBusiness" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Detail" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CycleDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="PlanCode" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *                   &lt;element name="Dcn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="SubscriberId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="TransactionId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                   &lt;element name="PayeeIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="PriorClaimPaidAmount"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;float"&gt;
 *                           &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="ClaimPaidAmount"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;float"&gt;
 *                           &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="DateGroupCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="PlanType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="CoderId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="OcProcessedDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="TaxId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                   &lt;element name="CustomElements"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="CustomElement"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Trailer"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="RecordCount" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="RecordTotal"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;float"&gt;
 *                           &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "detail",
    "trailer"
})
@XmlRootElement(name = "CashManagementTransaction")
public class CashManagementTransaction {

    @XmlElement(name = "Header", required = true)
    protected CashManagementTransaction.Header header;
    @XmlElement(name = "Detail")
    protected List<CashManagementTransaction.Detail> detail;
    @XmlElement(name = "Trailer", required = true)
    protected CashManagementTransaction.Trailer trailer;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link CashManagementTransaction.Header }
     *     
     */
    public CashManagementTransaction.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link CashManagementTransaction.Header }
     *     
     */
    public void setHeader(CashManagementTransaction.Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the detail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CashManagementTransaction.Detail }
     * 
     * 
     */
    public List<CashManagementTransaction.Detail> getDetail() {
        if (detail == null) {
            detail = new ArrayList<CashManagementTransaction.Detail>();
        }
        return this.detail;
    }

    /**
     * Gets the value of the trailer property.
     * 
     * @return
     *     possible object is
     *     {@link CashManagementTransaction.Trailer }
     *     
     */
    public CashManagementTransaction.Trailer getTrailer() {
        return trailer;
    }

    /**
     * Sets the value of the trailer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CashManagementTransaction.Trailer }
     *     
     */
    public void setTrailer(CashManagementTransaction.Trailer value) {
        this.trailer = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="CycleDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="PlanCode" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
     *         &lt;element name="Dcn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="SubscriberId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="TransactionId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *         &lt;element name="PayeeIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="PriorClaimPaidAmount"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;float"&gt;
     *                 &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="ClaimPaidAmount"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;float"&gt;
     *                 &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="DateGroupCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="PlanType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="CoderId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="OcProcessedDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="TaxId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
     *         &lt;element name="CustomElements"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="CustomElement"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cycleDate",
        "planCode",
        "dcn",
        "subscriberId",
        "transactionId",
        "payeeIdentifier",
        "priorClaimPaidAmount",
        "claimPaidAmount",
        "dateGroupCode",
        "planType",
        "coderId",
        "ocProcessedDate",
        "taxId",
        "customElements"
    })
    public static class Detail {

        @XmlElement(name = "CycleDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar cycleDate;
        @XmlElement(name = "PlanCode")
        protected short planCode;
        @XmlElement(name = "Dcn", required = true)
        protected String dcn;
        @XmlElement(name = "SubscriberId", required = true)
        protected String subscriberId;
        @XmlElement(name = "TransactionId")
        protected long transactionId;
        @XmlElement(name = "PayeeIdentifier", required = true)
        protected String payeeIdentifier;
        @XmlElement(name = "PriorClaimPaidAmount", required = true)
        protected CashManagementTransaction.Detail.PriorClaimPaidAmount priorClaimPaidAmount;
        @XmlElement(name = "ClaimPaidAmount", required = true)
        protected CashManagementTransaction.Detail.ClaimPaidAmount claimPaidAmount;
        @XmlElement(name = "DateGroupCode", required = true)
        protected String dateGroupCode;
        @XmlElement(name = "PlanType", required = true)
        protected String planType;
        @XmlElement(name = "CoderId", required = true)
        protected String coderId;
        @XmlElement(name = "OcProcessedDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar ocProcessedDate;
        @XmlElement(name = "TaxId")
        protected Integer taxId;
        @XmlElement(name = "CustomElements", required = true)
        protected CashManagementTransaction.Detail.CustomElements customElements;

        /**
         * Gets the value of the cycleDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCycleDate() {
            return cycleDate;
        }

        /**
         * Sets the value of the cycleDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCycleDate(XMLGregorianCalendar value) {
            this.cycleDate = value;
        }

        /**
         * Gets the value of the planCode property.
         * 
         */
        public short getPlanCode() {
            return planCode;
        }

        /**
         * Sets the value of the planCode property.
         * 
         */
        public void setPlanCode(short value) {
            this.planCode = value;
        }

        /**
         * Gets the value of the dcn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDcn() {
            return dcn;
        }

        /**
         * Sets the value of the dcn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDcn(String value) {
            this.dcn = value;
        }

        /**
         * Gets the value of the subscriberId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubscriberId() {
            return subscriberId;
        }

        /**
         * Sets the value of the subscriberId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubscriberId(String value) {
            this.subscriberId = value;
        }

        /**
         * Gets the value of the transactionId property.
         * 
         */
        public long getTransactionId() {
            return transactionId;
        }

        /**
         * Sets the value of the transactionId property.
         * 
         */
        public void setTransactionId(long value) {
            this.transactionId = value;
        }

        /**
         * Gets the value of the payeeIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPayeeIdentifier() {
            return payeeIdentifier;
        }

        /**
         * Sets the value of the payeeIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPayeeIdentifier(String value) {
            this.payeeIdentifier = value;
        }

        /**
         * Gets the value of the priorClaimPaidAmount property.
         * 
         * @return
         *     possible object is
         *     {@link CashManagementTransaction.Detail.PriorClaimPaidAmount }
         *     
         */
        public CashManagementTransaction.Detail.PriorClaimPaidAmount getPriorClaimPaidAmount() {
            return priorClaimPaidAmount;
        }

        /**
         * Sets the value of the priorClaimPaidAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link CashManagementTransaction.Detail.PriorClaimPaidAmount }
         *     
         */
        public void setPriorClaimPaidAmount(CashManagementTransaction.Detail.PriorClaimPaidAmount value) {
            this.priorClaimPaidAmount = value;
        }

        /**
         * Gets the value of the claimPaidAmount property.
         * 
         * @return
         *     possible object is
         *     {@link CashManagementTransaction.Detail.ClaimPaidAmount }
         *     
         */
        public CashManagementTransaction.Detail.ClaimPaidAmount getClaimPaidAmount() {
            return claimPaidAmount;
        }

        /**
         * Sets the value of the claimPaidAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link CashManagementTransaction.Detail.ClaimPaidAmount }
         *     
         */
        public void setClaimPaidAmount(CashManagementTransaction.Detail.ClaimPaidAmount value) {
            this.claimPaidAmount = value;
        }

        /**
         * Gets the value of the dateGroupCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDateGroupCode() {
            return dateGroupCode;
        }

        /**
         * Sets the value of the dateGroupCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDateGroupCode(String value) {
            this.dateGroupCode = value;
        }

        /**
         * Gets the value of the planType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanType() {
            return planType;
        }

        /**
         * Sets the value of the planType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanType(String value) {
            this.planType = value;
        }

        /**
         * Gets the value of the coderId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCoderId() {
            return coderId;
        }

        /**
         * Sets the value of the coderId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCoderId(String value) {
            this.coderId = value;
        }

        /**
         * Gets the value of the ocProcessedDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getOcProcessedDate() {
            return ocProcessedDate;
        }

        /**
         * Sets the value of the ocProcessedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setOcProcessedDate(XMLGregorianCalendar value) {
            this.ocProcessedDate = value;
        }

        /**
         * Gets the value of the taxId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTaxId() {
            return taxId;
        }

        /**
         * Sets the value of the taxId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTaxId(Integer value) {
            this.taxId = value;
        }

        /**
         * Gets the value of the customElements property.
         * 
         * @return
         *     possible object is
         *     {@link CashManagementTransaction.Detail.CustomElements }
         *     
         */
        public CashManagementTransaction.Detail.CustomElements getCustomElements() {
            return customElements;
        }

        /**
         * Sets the value of the customElements property.
         * 
         * @param value
         *     allowed object is
         *     {@link CashManagementTransaction.Detail.CustomElements }
         *     
         */
        public void setCustomElements(CashManagementTransaction.Detail.CustomElements value) {
            this.customElements = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;float"&gt;
         *       &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class ClaimPaidAmount {

            @XmlValue
            protected float value;
            @XmlAttribute(name = "currency")
            protected String currency;

            /**
             * Gets the value of the value property.
             * 
             */
            public float getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(float value) {
                this.value = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrency(String value) {
                this.currency = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="CustomElement"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "customElement"
        })
        public static class CustomElements {

            @XmlElement(name = "CustomElement", required = true)
            protected CashManagementTransaction.Detail.CustomElements.CustomElement customElement;

            /**
             * Gets the value of the customElement property.
             * 
             * @return
             *     possible object is
             *     {@link CashManagementTransaction.Detail.CustomElements.CustomElement }
             *     
             */
            public CashManagementTransaction.Detail.CustomElements.CustomElement getCustomElement() {
                return customElement;
            }

            /**
             * Sets the value of the customElement property.
             * 
             * @param value
             *     allowed object is
             *     {@link CashManagementTransaction.Detail.CustomElements.CustomElement }
             *     
             */
            public void setCustomElement(CashManagementTransaction.Detail.CustomElements.CustomElement value) {
                this.customElement = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class CustomElement {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "name")
                protected String name;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;float"&gt;
         *       &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class PriorClaimPaidAmount {

            @XmlValue
            protected float value;
            @XmlAttribute(name = "currency")
            protected String currency;

            /**
             * Gets the value of the value property.
             * 
             */
            public float getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(float value) {
                this.value = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrency(String value) {
                this.currency = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="PlanOrganization" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ActivityTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *         &lt;element name="LineOfBusiness" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "planOrganization",
        "activityTimestamp",
        "lineOfBusiness"
    })
    public static class Header {

        @XmlElement(name = "PlanOrganization", required = true)
        protected String planOrganization;
        @XmlElement(name = "ActivityTimestamp", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar activityTimestamp;
        @XmlElement(name = "LineOfBusiness", required = true)
        protected String lineOfBusiness;

        /**
         * Gets the value of the planOrganization property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanOrganization() {
            return planOrganization;
        }

        /**
         * Sets the value of the planOrganization property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanOrganization(String value) {
            this.planOrganization = value;
        }

        /**
         * Gets the value of the activityTimestamp property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getActivityTimestamp() {
            return activityTimestamp;
        }

        /**
         * Sets the value of the activityTimestamp property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setActivityTimestamp(XMLGregorianCalendar value) {
            this.activityTimestamp = value;
        }

        /**
         * Gets the value of the lineOfBusiness property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLineOfBusiness() {
            return lineOfBusiness;
        }

        /**
         * Sets the value of the lineOfBusiness property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLineOfBusiness(String value) {
            this.lineOfBusiness = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="RecordCount" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
     *         &lt;element name="RecordTotal"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;float"&gt;
     *                 &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "recordCount",
        "recordTotal"
    })
    public static class Trailer {

        @XmlElement(name = "RecordCount")
        protected byte recordCount;
        @XmlElement(name = "RecordTotal", required = true)
        protected CashManagementTransaction.Trailer.RecordTotal recordTotal;

        /**
         * Gets the value of the recordCount property.
         * 
         */
        public byte getRecordCount() {
            return recordCount;
        }

        /**
         * Sets the value of the recordCount property.
         * 
         */
        public void setRecordCount(byte value) {
            this.recordCount = value;
        }

        /**
         * Gets the value of the recordTotal property.
         * 
         * @return
         *     possible object is
         *     {@link CashManagementTransaction.Trailer.RecordTotal }
         *     
         */
        public CashManagementTransaction.Trailer.RecordTotal getRecordTotal() {
            return recordTotal;
        }

        /**
         * Sets the value of the recordTotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link CashManagementTransaction.Trailer.RecordTotal }
         *     
         */
        public void setRecordTotal(CashManagementTransaction.Trailer.RecordTotal value) {
            this.recordTotal = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;float"&gt;
         *       &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class RecordTotal {

            @XmlValue
            protected float value;
            @XmlAttribute(name = "currency")
            protected String currency;

            /**
             * Gets the value of the value property.
             * 
             */
            public float getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(float value) {
                this.value = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrency(String value) {
                this.currency = value;
            }

        }

    }

}
