//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.15 at 07:03:23 PM IST 
//


package testProj.test;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the testProj.test package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: testProj.test
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CashManagementTransaction }
     * 
     */
    public CashManagementTransaction createCashManagementTransaction() {
        return new CashManagementTransaction();
    }

    /**
     * Create an instance of {@link CashManagementTransaction.Trailer }
     * 
     */
    public CashManagementTransaction.Trailer createCashManagementTransactionTrailer() {
        return new CashManagementTransaction.Trailer();
    }

    /**
     * Create an instance of {@link CashManagementTransaction.Detail }
     * 
     */
    public CashManagementTransaction.Detail createCashManagementTransactionDetail() {
        return new CashManagementTransaction.Detail();
    }

    /**
     * Create an instance of {@link CashManagementTransaction.Detail.CustomElements }
     * 
     */
    public CashManagementTransaction.Detail.CustomElements createCashManagementTransactionDetailCustomElements() {
        return new CashManagementTransaction.Detail.CustomElements();
    }

    /**
     * Create an instance of {@link CashManagementTransaction.Header }
     * 
     */
    public CashManagementTransaction.Header createCashManagementTransactionHeader() {
        return new CashManagementTransaction.Header();
    }

    /**
     * Create an instance of {@link CashManagementTransaction.Trailer.RecordTotal }
     * 
     */
    public CashManagementTransaction.Trailer.RecordTotal createCashManagementTransactionTrailerRecordTotal() {
        return new CashManagementTransaction.Trailer.RecordTotal();
    }

    /**
     * Create an instance of {@link CashManagementTransaction.Detail.PriorClaimPaidAmount }
     * 
     */
    public CashManagementTransaction.Detail.PriorClaimPaidAmount createCashManagementTransactionDetailPriorClaimPaidAmount() {
        return new CashManagementTransaction.Detail.PriorClaimPaidAmount();
    }

    /**
     * Create an instance of {@link CashManagementTransaction.Detail.ClaimPaidAmount }
     * 
     */
    public CashManagementTransaction.Detail.ClaimPaidAmount createCashManagementTransactionDetailClaimPaidAmount() {
        return new CashManagementTransaction.Detail.ClaimPaidAmount();
    }

    /**
     * Create an instance of {@link CashManagementTransaction.Detail.CustomElements.CustomElement }
     * 
     */
    public CashManagementTransaction.Detail.CustomElements.CustomElement createCashManagementTransactionDetailCustomElementsCustomElement() {
        return new CashManagementTransaction.Detail.CustomElements.CustomElement();
    }

}
